// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func initializeApp() *App {
	stdout := provideStdout()
	stderr := provideStderr()
	app := NewApp(stdout, stderr)
	return app
}
